### ISSUE TITLE
Error on getting Favorites

### ISSUE THREAD

**Issue by hencou** [brianhornsby/plugin.audio.tuneinradio#115] opened 2018-01-28 12:31 UTC
Thanks for your great work!

Found a problem in Favorites in the latest 3.0 development version:
When I click on Favorites, Kodi gives an error.
When I change __partnerid__ = 'yvcOjvJP' to __partnerid__ = 'RadioTime' in "default.py" the Favorites are working again.

**Comment by brianhornsby** [comment] 2018-02-13 04:33
Duplicate of issue #111, so closing issue.

**Closed by brianhornsby** 2018-02-13 04:33 UTC
Labels: duplicate
