### ISSUE TITLE
Raspberry Kodi 17.4 addon error

### ISSUE THREAD

**Issue by xtrem007** [brianhornsby/plugin.audio.tuneinradio#112] opened 2017-12-03 15:33 UTC
Can't start tuneinradio plugin on Raspberry Kodi 17.4

16:19:54.504 T:1530995632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.audio.tuneinradio/default.py", line 1029, in <module>
                                                results = __tunein__.browse_presets(username=__username__)
                                              File "/home/pi/.kodi/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 368, in browse_presets
                                                result = self.__call_tunein('Browse.ashx', params)
                                              File "/home/pi/.kodi/addons/plugin.audio.tuneinradio/resources/lib/tunein.py", line 103, in __call_tunein
                                                f = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
16:19:54.746 T:1946288800   ERROR: GetDirectory - Error getting plugin://plugin.audio.tuneinradio/
16:19:54.746 T:1946288800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.tuneinradio/) failed

**Comment by brianhornsby** [comment] 2017-12-03 22:51
Duplicate of issue #111

**Comment by brianhornsby** [comment] 2017-12-06 23:04
TuneIn appear to have revoked my access to the API methods used for presets. You can fix it manually by editing the default.py file and setting the variable partnerid to ‘HyzqumNX’

**Closed by brianhornsby** 2017-12-06 23:04 UTC
